# Generated by Django 4.2.6 on 2023-10-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category_Receipe',
            new_name='Category_Recipe',
        ),
        migrations.RenameField(
            model_name='category_recipe',
            old_name='receipe',
            new_name='recipe',
        ),
    ]
