# Generated by Django 4.2.6 on 2023-11-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['id']},
        ),
    ]
